services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: macintosh
      MYSQL_DATABASE: autoverleih
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306